version: '3'
services:
  app:
    image: node:14.17.0
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd front-root && npm run build && npm run start"
    ports:
      - "3000:3000"