import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "@/src/styles/Home.module.css";
import Stack from "@mui/material/Stack";
import Button from "@mui/material/Button";
import { useRecoilValue } from "recoil";
import { sampleAtomValue } from "@/src/recoilStates";

const Home: NextPage = () => {
  const sampleAtom = useRecoilValue(sampleAtomValue);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Hello World <br />
        {sampleAtom} <br />
        <Stack spacing={2} direction="row">
          <Button variant="text">Text</Button>
          <Button variant="contained">Contained</Button>
          <Button variant="outlined">Outlined</Button> <br />
        </Stack>
        <a href="/about">about</a>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
